//
// This is a simple example of calculating a square-root, using
// a UTF-8 symbol!
//
// You can run this via the `evalfilter` command like so:
//
//    $ evalfilter run math.script
//
// Once you do so you'll see the output, and the return-code displayed:
//
//    $ evalfilter run math.script
//    Mathematics is fun
//    Script gave result type:BOOLEAN value:false - which is 'false'.
//

if ( √9 == 3 ) { print("Mathematics is fun\n"); }

return false;
