//
// This is a simple on-call script.
//


if ( Channel !~ /_ALerts$/i ) {
    print("The channel `" + Channel + "` is not important\n");
    return false;
}


//
// We'll ignore messages from staff-members.
//
// Here's our list of members to ignore.
//
staff = [ "Alice", "Bob", "Chris", "Diane" ];

//
// Got a match?  We're done
//
if ( Author in staff ) {
    print( "Ignoring message from staff-member ", Author, "\n" );
    return false;
}


print( "Raising alert!\n");
return true;
